<a href="https://colab.research.google.com/github/O-Aiden/CartoonGuidetoStatisticsByPython/blob/main/13_%E3%80%8A%E6%BC%AB%E7%94%BB%E7%BB%9F%E8%AE%A1%E5%AD%A6%E4%B9%8B%E5%9B%A0%E5%AD%90%E5%88%86%E6%9E%90%E3%80%8Bpython%E5%AE%9E%E7%8E%B0_%E6%8A%BD%E6%A0%B7%E6%96%B9%E6%B3%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import pandas as pd

data = pd.read_excel('汽车企业销量数据.xlsx',index_col=0)
data.head(5)

       企业  2021-05-01 00:00:00  2021-04-01 00:00:00  ...   2021年    2020年    2019年
序号                                                   ...
1    上海大众               110000               108301  ...  467401  1505559  1812637
2   一汽-大众               111518                83026  ...  554629  1415462  1416775
3    吉利汽车                96581               100846  ...  531859  1315408  1362608
4    上汽通用                69729                66927  ...  420357  1271652  1510456
5    东风日产                79277                84499  ...  409188  1119008  1159108

[5 rows x 10 columns]

# 简单随机抽样

In [141]:
len(data.sample(n=20))

20

# 分层抽样

In [142]:
temp = data[['企业','2021年']]
# 总样本
temp['2021年'].sum()
# 各汽车销量占总样本的比例
temp['频率'] = temp['2021年']/temp['2021年'].sum()
# 设定总过抽样180例
temp['抽样'] = 180*temp['频率']
# 四舍五入
temp['抽样'] = (temp['抽样']+0.5).astype(int)
temp.head(5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

       企业   2021年        频率  抽样
序号
1    上海大众  467401  0.055516  10
2   一汽-大众  554629  0.065877  12
3    吉利汽车  531859  0.063172  11
4    上汽通用  420357  0.049928   9
5    东风日产  409188  0.048602   9

# 二阶抽样

In [179]:
temp = data[['企业','2021年']]
# 求累计销量
temp['累计销量'] = temp['2021年'].cumsum()
# 求累计下限
temp['累计销量下限'] = temp['累计销量'] - temp['2021年'] + 1 
# 求累计上限
temp['累计销量上限'] = temp['累计销量']
temp.head(5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

       企业   2021年     累计销量   累计销量下限   累计销量上限
序号
1    上海大众  467401   467401        1   467401
2   一汽-大众  554629  1022030   467402  1022030
3    吉利汽车  531859  1553889  1022031  1553889
4    上汽通用  420357  1974246  1553890  1974246
5    东风日产  409188  2383434  1974247  2383434

## 步骤一：求出10个随机数

In [180]:
import random
 
rands = [random.randint(1,temp['2021年'].sum()) for _ in range(10)]
rands

[4423938,
 6358638,
 6071491,
 3624384,
 1164907,
 3272329,
 639166,
 4935982,
 4125657,
 7317823]

## 步骤二：随机数介于累计上限和下限值之间的汽车企业

In [181]:
names = []
for rand in rands:
  a = temp.loc[(temp['累计销量下限']<rand) & (temp['累计销量上限']>rand),['企业']]
  names.append([int(a.index.values),a['企业'].to_list()[0],int(rand)])
names

[[10, '广汽本田', 4423938],
 [17, '华晨宝马', 6358638],
 [16, '北京奔驰', 6071491],
 [8, '长城汽车', 3624384],
 [3, '吉利汽车', 1164907],
 [7, '长安汽车', 3272329],
 [2, '一汽-大众', 639166],
 [12, '广汽丰田', 4935982],
 [9, '东风本田', 4125657],
 [23, '一汽吉林', 7317823]]

## 步骤三：在这10个随机抽出的企业中再随机抽取的相同数量的汽车

# 分层二阶抽样

## 先对2021年所有企业进行分层

In [236]:
temp_samp = data[['企业','2021年']]
temp_samp = temp_samp.loc[(temp_samp['2021年'] != 0)]
temp_samp['2021年'].sum()
temp_samp['频率'] = temp_samp['2021年']/temp_samp['2021年'].sum()
# 设定总过抽样180例
temp_samp['抽样'] = 1800*temp_samp['频率']
# 四舍五入
temp_samp['抽样'] = (temp_samp['抽样']+0.5).astype(int)
temp_samp.head(5)

       企业   2021年        频率   抽样
序号
1    上海大众  467401  0.055516  100
2   一汽-大众  554629  0.065877  119
3    吉利汽车  531859  0.063172  114
4    上汽通用  420357  0.049928   90
5    东风日产  409188  0.048602   87

## 再进行二阶抽样

In [ ]:
# import random
# data.columns = ['企业','五月','四月','三月','二月','一月','上年十二月','2021年', '2020年', '2019年']
# temp1 = data[['企业','五月','四月','三月','二月','一月']]
# # 将企业列设为索引列
# temp1.set_index('企业', inplace=True)
# # 删除这五个月总销量为0的企业
# temp1 = temp1.loc[(temp1.sum(axis=1) != 0)]
# temp1.tail(5)
# # 对行列进行转置
# temp1_T = temp1.T
# temp1_T.head(5)

# data_copy = data.copy()
# # 删除2021年销量为0的企业
# data_copy = data_copy.loc[(data_copy['2021年'] != 0)]
# data_copy.set_index('企业', inplace=True)
# companys = data_copy.index.values
# all_names = []
# for company in companys: 
#   ## 随机抽取三个月份
#   rands = [random.randint(1,data_copy['2021年'][company]) for _ in range(3)]
#   # print(rands)

#   ## 计算累积上限和下限
#   temp = temp1_T[[company]]
#   # 求累计销量
#   temp['累计销量'] = temp1_T[company].cumsum()
#   # 求累计下限
#   temp['累计销量下限'] = temp['累计销量'] - temp1_T[company] + 1 
#   # 求累计上限
#   temp['累计销量上限'] = temp['累计销量']
  
#   temp.index.names = ['月份']
#   temp = temp.reset_index()
#   # print(temp.index)
  
#   ## 具体对每个企业的哪几个月销量进行抽样
#   names = []
#   for rand in rands:
#     a = temp.loc[(temp['累计销量下限']<=rand) & (temp['累计销量上限']>=rand),['月份']]
#     names.append([int(a.index.values),a['月份'].to_list()[0],int(rand)])
#   all_names.append(names)

In [ ]:
import random
data.columns = ['企业','五月','四月','三月','二月','一月','上年十二月','2021年', '2020年', '2019年']
temp1 = data[['企业','五月','四月','三月','二月','一月']]
# 将企业列设为索引列
temp1.set_index('企业', inplace=True)
# 删除这五个月总销量为0的企业
temp1 = temp1.loc[(temp1.sum(axis=1) != 0)]
temp1.tail(5)
# 对行列进行转置
temp1_T = temp1.T
temp1_T.head(5)

data_copy = data.copy()
# 删除2021年销量为0的企业
data_copy = data_copy.loc[(data_copy['2021年'] != 0)]
data_copy.set_index('企业', inplace=True)
companys = data_copy.index.values
all_names = []
for company in companys: 
  ## 随机抽取三个月份
  rands = [random.randint(1,data_copy['2021年'][company]) for _ in range(3)]
  # print(rands)

  ## 计算累积上限和下限
  temp = temp1_T[[company]]
  # 求累计销量
  temp['累计销量'] = temp1_T[company].cumsum()
  # 求累计下限
  temp['累计销量下限'] = temp['累计销量'] - temp1_T[company] + 1 
  # 求累计上限
  temp['累计销量上限'] = temp['累计销量']
  
  temp.index.names = ['月份']
  temp = temp.reset_index()
  # print(temp.index)
  
  ## 具体对每个企业的哪几个月销量进行抽样
  names = []
  for rand in rands:
    a = temp.loc[(temp['累计销量下限']<=rand) & (temp['累计销量上限']>=rand),['月份']]
    names.append(a['月份'].to_list()[0])
  all_names.append([company,names])

In [237]:
all_names

[['上海大众', ['二月', '三月', '三月']],
 ['一汽-大众', ['一月', '三月', '一月']],
 ['吉利汽车', ['二月', '一月', '一月']],
 ['上汽通用', ['一月', '三月', '三月']],
 ['东风日产', ['二月', '一月', '五月']],
 ['上汽通用五菱', ['三月', '四月', '二月']],
 ['长安汽车', ['三月', '二月', '一月']],
 ['长城汽车', ['一月', '三月', '一月']],
 ['东风本田', ['一月', '一月', '二月']],
 ['广汽本田', ['四月', '一月', '三月']],
 ['一汽丰田', ['一月', '一月', '三月']],
 ['广汽丰田', ['五月', '三月', '五月']],
 ['上海汽车', ['四月', '一月', '二月']],
 ['一汽奥迪', ['五月', '四月', '一月']],
 ['奇瑞汽车', ['一月', '四月', '二月']],
 ['北京奔驰', ['四月', '二月', '四月']],
 ['华晨宝马', ['一月', '三月', '二月']],
 ['北京现代', ['一月', '一月', '三月']],
 ['比亚迪汽车', ['一月', '一月', '三月']],
 ['广汽乘用车', ['二月', '二月', '一月']],
 ['东风悦达起亚', ['五月', '一月', '五月']],
 ['长安福特', ['一月', '五月', '一月']],
 ['一汽吉林', ['四月', '一月', '五月']],
 ['菲斯科', ['二月', '二月', '三月']],
 ['沃尔沃亚太', ['五月', '五月', '二月']],
 ['一汽轿车', ['四月', '三月', '一月']],
 ['东风渝安', ['四月', '一月', '五月']],
 ['长安马自达', ['五月', '五月', '二月']],
 ['华晨鑫源', ['一月', '四月', '五月']],
 ['Tesla Motors', ['三月', '五月', '三月']],
 ['江淮汽车', ['四月', '四月', '一月']],
 ['BEIJING汽车', ['五月', '二月', '二月']],
 ['东风风行', ['四月', '五月', '五月']],
 ['东风启辰', ['四月', '三月', '二月']],
 ['广汽三菱', ['五月', '五月', '三月']],
 ['东风乘用车', ['三月', '一月', '四月']],
 ['广汽埃安新能源汽车有限公司', ['三月', '五月', '一月']],
 ['奇瑞捷豹路虎', ['一月', '三月', '一月']],
 ['江铃汽车', ['四月', '五月', '五月']],
 ['神龙汽车', ['四月', '四月', '四月']],
 ['上汽大通', ['四月', '二月', '五月']],
 ['蔚来汽车', ['五月', '五月', '一月']],
 ['长安林肯', ['一月', '五月', '三月']],
 ['广汽菲克', ['二月', '四月', '四月']],
 ['凯翼汽车', ['三月', '二月', '一月']],
 ['福建奔驰', ['四月', '一月', '三月']],
 ['车和家', ['一月', '三月', '四月']],
 ['东风英菲尼迪', ['三月', '三月', '四月']],
 ['潍柴汽车', ['五月', '三月', '三月']],
 ['威马汽车', ['五月', '五月', '五月']],
 ['小鹏汽车', ['三月', '一月', '四月']],
 ['北汽新能源', ['三月', '一月', '四月']],
 ['长安铃木', ['一月', '五月', '五月']],
 ['东南汽车', ['三月', '一月', '三月']],
 ['观致汽车', ['二月', '四月', '二月']],
 ['郑州日产', ['一月', '二月', '五月']],
 ['合众新能源', ['五月', '五月', '三月']],
 ['宝沃', ['三月', '四月', '三月']],
 ['华晨金杯', ['一月', '一月', '一月']],
 ['其他车厂', ['二月', '三月', '五月']],
 ['福田汽车', ['四月', '四月', '四月']],
 ['昌河汽车', ['四月', '五月', '五月']],
 ['昌河铃木', ['四月', '一月', '三月']],
 ['海马汽车', ['五月', '三月', '三月']],
 ['北汽制造', ['五月', '四月', '五月']],
 ['云度汽车', ['三月', '一月', '四月']],
 ['江淮大众', ['三月', '五月', '五月']],
 ['福汽新龙马', ['四月', '二月', '五月']],
 ['北汽银翔', ['五月', '五月', '五月']],
 ['北汽威旺', ['三月', '二月', '三月']],
 ['江西五十铃', ['五月', '五月', '五月']],
 ['东风雷诺', ['二月', '一月', '一月']],
 ['国机智骏', ['五月', '一月', '五月']],
 ['金康SERES', ['五月', '五月', '五月']],
 ['爱驰汽车', ['四月', '三月', '三月']],
 ['吉麦新能源', ['五月', '一月', '一月']],
 ['广汽蔚来', ['一月', '三月', '一月']],
 ['力帆汽车', ['三月', '三月', '三月']],
 ['南京菲亚特', ['三月', '三月', '三月']]]

In [235]:
## 对数据进行合并
data_samp = pd.DataFrame(all_names)
data_samp.columns = ['企业','抽样月份']
temp_samp_copy = temp_samp.copy()

temp_samp_copy.set_index('企业', inplace=True)
data_samp.set_index('企业', inplace=True)

result = pd.concat([data_samp,temp_samp_copy], axis=1).dropna()
result['每月抽样'] = (result['抽样']/3 + 0.5).astype(int)
result = result.loc[(result['每月抽样'] != 0)]

result

                       抽样月份   2021年        频率   抽样  每月抽样
企业
上海大众           [二月, 三月, 三月]  467401  0.055516  100    33
一汽-大众          [一月, 三月, 一月]  554629  0.065877  119    40
吉利汽车           [二月, 一月, 一月]  531859  0.063172  114    38
上汽通用           [一月, 三月, 三月]  420357  0.049928   90    30
东风日产           [二月, 一月, 五月]  409188  0.048602   87    29
上汽通用五菱         [三月, 四月, 二月]  417963  0.049644   89    30
长安汽车           [三月, 二月, 一月]  581283  0.069043  124    41
长城汽车           [一月, 三月, 一月]  417541  0.049594   89    30
东风本田           [一月, 一月, 二月]  333618  0.039626   71    24
广汽本田           [四月, 一月, 三月]  319133  0.037905   68    23
一汽丰田           [一月, 一月, 三月]  343352  0.040782   73    24
广汽丰田           [五月, 三月, 五月]  344018  0.040861   74    25
上海汽车           [四月, 一月, 二月]  252373  0.029976   54    18
一汽奥迪           [五月, 四月, 一月]  313580  0.037246   67    22
奇瑞汽车           [一月, 四月, 二月]  301838  0.035851   65    22
北京奔驰           [四月, 二月, 四月]  275481  0.032721   59    20
华晨宝马           [一月, 三月, 二月]  304733  0.036195   65    22
北京现代           [一月, 一月, 三月]  161934  0.019234   35    12
比亚迪汽车          [一月, 一月, 三月]  193357  0.022966   41    14
广汽乘用车          [二月, 二月, 一月]  126027  0.014969   27     9
东风悦达起亚         [五月, 一月, 五月]   65759  0.007811   14     5
长安福特           [一月, 五月, 一月]   69956  0.008309   15     5
一汽吉林           [四月, 一月, 五月]  118096  0.014027   25     8
菲斯科            [二月, 二月, 三月]   75833  0.009007   16     5
沃尔沃亚太          [五月, 五月, 二月]   74658  0.008868   16     5
一汽轿车           [四月, 三月, 一月]   44874  0.005330   10     3
东风渝安           [四月, 一月, 五月]   76525  0.009089   16     5
长安马自达          [五月, 五月, 二月]   50262  0.005970   11     4
华晨鑫源           [一月, 四月, 五月]   54215  0.006439   12     4
Tesla Motors   [三月, 五月, 三月]  128588  0.015273   27     9
江淮汽车           [四月, 四月, 一月]   42998  0.005107    9     3
BEIJING汽车      [五月, 二月, 二月]   29557  0.003511    6     2
东风风行           [四月, 五月, 五月]   50664  0.006018   11     4
东风启辰           [四月, 三月, 二月]   24827  0.002949    5     2
广汽三菱           [五月, 五月, 三月]   25206  0.002994    5     2
东风乘用车          [三月, 一月, 四月]   32860  0.003903    7     2
广汽埃安新能源汽车有限公司  [三月, 五月, 一月]   32329  0.003840    7     2
奇瑞捷豹路虎         [一月, 三月, 一月]   22204  0.002637    5     2
江铃汽车           [四月, 五月, 五月]   20130  0.002391    4     1
神龙汽车           [四月, 四月, 四月]   32768  0.003892    7     2
上汽大通           [四月, 二月, 五月]   18010  0.002139    4     1
蔚来汽车           [五月, 五月, 一月]   36064  0.004284    8     3
长安林肯           [一月, 五月, 三月]   30107  0.003576    6     2
广汽菲克           [二月, 四月, 四月]   11205  0.001331    2     1
凯翼汽车           [三月, 二月, 一月]    7498  0.000891    2     1
福建奔驰           [四月, 一月, 三月]   15537  0.001845    3     1
车和家            [一月, 三月, 四月]   22441  0.002665    5     2
威马汽车           [五月, 五月, 五月]   11658  0.001385    2     1
小鹏汽车           [三月, 一月, 四月]   24187  0.002873    5     2
合众新能源          [五月, 五月, 三月]   15966  0.001896    3     1
其他车厂           [二月, 三月, 五月]   12801  0.001520    3     1
江淮大众           [三月, 五月, 五月]   20663  0.002454    4     1